-- Add order_number identity, payments table, and indexes for orders
-- Run this in Supabase SQL editor or psql as a migration

-- 1) Add order_number column if not exists
ALTER TABLE IF EXISTS public.orders
  ADD COLUMN IF NOT EXISTS order_number bigint GENERATED BY DEFAULT AS IDENTITY;

-- 2) Payments table
CREATE TABLE IF NOT EXISTS public.payments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id uuid REFERENCES public.orders(id) ON DELETE CASCADE,
  amount numeric(12,2) NOT NULL,
  method text,
  reference text,
  created_at timestamptz DEFAULT now()
);

-- 3) Single active order per table (partial unique index)
-- Ensures only one order with status IN ('open','held') exists per table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'one_active_order_per_table'
  ) THEN
    CREATE UNIQUE INDEX one_active_order_per_table ON public.orders (table_id) WHERE status IN ('open','held');
  END IF;
END$$;

-- 4) Useful indexes for lookups
CREATE INDEX IF NOT EXISTS idx_orders_table_status_created_at ON public.orders(table_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
